name: Push a file to our repository

on: workflow_dispatch

jobs:
  create_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: Int
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install and run tests
        run: |
          python3 -m pip install --user pytest
          export PATH=$PATH:$HOME/.local/bin
          python3 -m pytest --tb=short 2>&1 | tee log_pytest.txt || true
      
      - name: Push a file to our repository
        env:
          ACTOR: ${{ github.actor }}
          REPOSITORY: ${{ github.repository }}
        run: |
          pwd
          ls -a
          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot"
          git remote set-url origin "https://$ACTOR:${{ secrets.TOKEN }}@github.com/$REPOSITORY.git"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull
          ls -a
          git add .
          git commit -m "random file from action"
          git push

